backend = "glx";
shadow = true;
fading = true;

shadow-exclude = [
  "class_g = 'dwm'",
  "! name~=''",
  #"x = 0 && y = 0 && override_redirect = true",
  "name = 'Notification'",
  "_GTK_FRAME_EXTENTS@:c"
];

blur-background-exclude = [
  "class_g = 'dwm'",
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

wintypes:
{
   dock = { opacity = 1.0; focus = true; shadow = false; }
   tooltip = { opacity = 1.0; focus = true; }
   popupmenu = { opacity = 1.0; focus = true; }
}
